//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kunicardus.Core {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ApplicationStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApplicationStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kunicardus.Core.ApplicationStrings", typeof(ApplicationStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ჩვენ შესახებ.
        /// </summary>
        internal static string AboutUs {
            get {
                return ResourceManager.GetString("AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to მიმდინარეობს ავტორიზაცია....
        /// </summary>
        internal static string Authorizing {
            get {
                return ResourceManager.GetString("Authorizing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to პინ-კოდის შეცვლა.
        /// </summary>
        internal static string ChangePin {
            get {
                return ResourceManager.GetString("ChangePin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to შეიყვანეთ არსებული პინ-კოდი.
        /// </summary>
        internal static string ChangePinPageTitle {
            get {
                return ResourceManager.GetString("ChangePinPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to დაგვიკავშირდით.
        /// </summary>
        internal static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to პაროლი უნდა შედგებოდეს 8 სიმბოლოსგან, შეიცავდეს ციფრებს და ლათინურ ასოებს.
        /// </summary>
        internal static string CorePasswordHint {
            get {
                return ResourceManager.GetString("CorePasswordHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to შეიყვანეთ ახალი პინ-კოდი.
        /// </summary>
        internal static string enter_new_pin {
            get {
                return ResourceManager.GetString("enter_new_pin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to გამარჯობა.
        /// </summary>
        internal static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to პინ-კოდი არასწორია.
        /// </summary>
        internal static string incorrect_pin {
            get {
                return ResourceManager.GetString("incorrect_pin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to მიმდინარეობს ჩატვირთვა....
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to სიახლეები.
        /// </summary>
        internal static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes:.
        /// </summary>
        internal static string NotesLabel {
            get {
                return ResourceManager.GetString("NotesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to პარტნიორები.
        /// </summary>
        internal static string Partners {
            get {
                return ResourceManager.GetString("Partners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to პინ-კოდი შეიცვალა.
        /// </summary>
        internal static string pin_changed_successfully {
            get {
                return ResourceManager.GetString("pin_changed_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to პინ-კოდი რეგისტრირებულია.
        /// </summary>
        internal static string pin_set_successfully {
            get {
                return ResourceManager.GetString("pin_set_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to მოთხოვნა  მუშავდება....
        /// </summary>
        internal static string ProcessingRequest {
            get {
                return ResourceManager.GetString("ProcessingRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to მიმდინარეობს რეგისტრაცია.
        /// </summary>
        internal static string Registering {
            get {
                return ResourceManager.GetString("Registering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to პინ-კოდი მოხსნილია.
        /// </summary>
        internal static string removed_pin_successfully {
            get {
                return ResourceManager.GetString("removed_pin_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to პინ-კოდის მოხსნა.
        /// </summary>
        internal static string RemovePin {
            get {
                return ResourceManager.GetString("RemovePin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to შეიყვანეთ პინ-კოდი.
        /// </summary>
        internal static string RemovePinPageTitle {
            get {
                return ResourceManager.GetString("RemovePinPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to გაიმეროთ ახალი პინ-კოდი.
        /// </summary>
        internal static string repeat_new_pin {
            get {
                return ResourceManager.GetString("repeat_new_pin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to განმეორებითი პინ-კოდი არასწორია.
        /// </summary>
        internal static string repeated_pin_incorrect {
            get {
                return ResourceManager.GetString("repeated_pin_incorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to პინ კოდის რეგისტრაცია.
        /// </summary>
        internal static string set_pin {
            get {
                return ResourceManager.GetString("set_pin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to პარამეტრები.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to მიმდინარეობს შემოწმება.
        /// </summary>
        internal static string SubmittingOTP {
            get {
                return ResourceManager.GetString("SubmittingOTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to მითითებული მომხმარებელი უკვე არსებობს.
        /// </summary>
        internal static string UserExists {
            get {
                return ResourceManager.GetString("UserExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to მითითებული ბარათით ტრანზაქცია ჯერ არ ჩატარებულა. გაატარეთ ბარათი უნიქარდის ნებისმიერ პარტნიორ კომპანიაში, შეინახეთ ბოლო ტრანზაქციის ჩეკი და განაახლეთ რეგისტრაციის პროცესი.
        /// </summary>
        internal static string ValidWithNoTransactions {
            get {
                return ResourceManager.GetString("ValidWithNoTransactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to გთხოვთ, შეიყვანოთ მითითებულ ნომერზე მოსული SMS კოდი.
        /// </summary>
        internal static string VerificationCodeIsNull {
            get {
                return ResourceManager.GetString("VerificationCodeIsNull", resourceCulture);
            }
        }
    }
}
